import { describe, expect, it } from "vitest";
import { readGolden } from "../../test/golden";
import {
  artefactsSample,
  experimentSample,
  projectSample,
  questionSample,
  requestCopySample,
  requestLinkSample,
} from "../../test/samples";
import {
  ArtefactsFile,
  ExperimentBody,
  ExperimentFrontmatter,
  InboxRequest,
  ProjectYaml,
  QuestionFrontmatter,
} from "../schema";
import type { Result } from "../result";
import { parseArtefacts, serialiseArtefacts } from "./artefacts";
import { parseExperiment, serialiseExperiment } from "./experiment";
import { parseProject, serialiseProject } from "./project";
import { parseQuestion, serialiseQuestion } from "./question";
import { parseRequest, serialiseRequest } from "./request";

/**
 * Canonical output compared with committed files (spec 5.2, gate S2-G01
 * until the fixtures of S2-T13 exist). The goldens were written by hand from
 * format-v1.md, not generated by the code under test.
 */

function expectByteIdentical<T>(
  name: string,
  parse: (text: string) => Result<T>,
  serialise: (value: T) => string,
): void {
  const golden = readGolden(name);
  const parsed = parse(golden);
  if (!parsed.ok) {
    throw new Error(`${name} did not parse: ${parsed.error.message}`);
  }
  expect(serialise(parsed.value)).toBe(golden);
}

const literature = [
  "## Literature",
  "",
  "1. Love, M. I., Huber, W. & Anders, S. Moderated estimation of fold change and dispersion for RNA-seq data with DESeq2. Genome Biol. 15, 550 (2014).",
].join("\n");

describe("serialise writes the committed canonical files", () => {
  it("project.yaml", async () => {
    await expect(
      serialiseProject(ProjectYaml.parse(projectSample)),
    ).toMatchFileSnapshot("../__golden__/project.yaml");
  });

  it("a question file", async () => {
    const text = serialiseQuestion({
      frontmatter: QuestionFrontmatter.parse(questionSample),
      body: [
        "Earlier pilots showed a strong separation between treated and control",
        "organoids, but the two groups were sequenced on different days.",
        "",
        "A second paragraph, kept exactly as written.",
      ].join("\n"),
    });
    await expect(text).toMatchFileSnapshot("../__golden__/question.md");
  });

  it("an experiment file with every recognised section and a literature block", async () => {
    const text = serialiseExperiment({
      frontmatter: ExperimentFrontmatter.parse(experimentSample),
      body: ExperimentBody.parse({
        preamble: "",
        sections: [
          {
            key: "methods",
            body: "PCA on variance-stabilised counts using DESeq2 [@z:u:7XK2PQ9M].",
          },
          {
            key: "results_notes",
            body: "Treatment groups separate along PC1.",
          },
          {
            key: "interpretation",
            body: "The PC1 separation is consistent with the treatment response reported previously [see @z:u:9HJ3LM2N, fig. 2].",
          },
        ],
        literature,
      }),
    });
    await expect(text).toMatchFileSnapshot("../__golden__/experiment.md");
  });

  it("artefacts.yaml", async () => {
    await expect(
      serialiseArtefacts(ArtefactsFile.parse(artefactsSample)),
    ).toMatchFileSnapshot("../__golden__/artefacts.yaml");
  });

  it("request.json in copy mode", async () => {
    await expect(
      serialiseRequest(InboxRequest.parse(requestCopySample)),
    ).toMatchFileSnapshot("../__golden__/request-copy.json");
  });

  it("request.json in link mode, keeping an unknown key", async () => {
    const request = InboxRequest.parse({
      ...requestLinkSample,
      x_future: { note: "unknown keys are kept", levels: [1, 2] },
    });
    await expect(serialiseRequest(request)).toMatchFileSnapshot(
      "../__golden__/request-link.json",
    );
  });
});

describe("serialise(parse(file)) is byte-identical for canonical files", () => {
  it("project.yaml", () => {
    expectByteIdentical("project.yaml", parseProject, serialiseProject);
  });
  it("a question file", () => {
    expectByteIdentical("question.md", parseQuestion, serialiseQuestion);
  });
  it("an experiment file", () => {
    expectByteIdentical("experiment.md", parseExperiment, serialiseExperiment);
  });
  it("an experiment file with a preamble, unknown keys and sections, fences and an empty literature block", () => {
    expectByteIdentical(
      "experiment-unknown-content.md",
      parseExperiment,
      serialiseExperiment,
    );
  });
  it("artefacts.yaml", () => {
    expectByteIdentical("artefacts.yaml", parseArtefacts, serialiseArtefacts);
  });
  it("request.json in copy mode", () => {
    expectByteIdentical("request-copy.json", parseRequest, serialiseRequest);
  });
  it("request.json in link mode", () => {
    expectByteIdentical("request-link.json", parseRequest, serialiseRequest);
  });
});
