import { sep, relative } from "node:path";

import {
  InboxRequest,
  type InboxRequestModel,
} from "@research-notebook/format";

import type { ProvenanceValue } from "./git-provenance";

/** RFC 3339 in UTC with second precision, the `timestamp` type (format-v1.md section 2). */
function formatTimestamp(date: Date): string {
  return date.toISOString().replace(/\.\d{3}Z$/, "Z");
}

/** `filePath` relative to `projectRoot`, forward-slash separated. `filePath`
 * must already be inside `projectRoot` (guaranteed by `findProjectRoot`). */
function toProjectRelativePath(projectRoot: string, filePath: string): string {
  return relative(projectRoot, filePath).split(sep).join("/");
}

/** What `buildInboxRequest` needs: values already decided elsewhere (the
 * chosen experiment, role and mode; the payload's own hash, size and, for
 * copy mode, its name in the request folder; any git provenance already
 * computed). This module only assembles and validates the request object —
 * it does no hashing, no git reading and no I/O. */
export interface BuildRequestInput {
  requestId: string;
  createdAt: Date;
  /** The running extension's own version, for `created_by` (FR-VSC-05). */
  extensionVersion: string;
  projectRoot: string;
  filePath: string;
  experimentId: string;
  role: "result" | "method";
  mode: "copy" | "link";
  sha256: string;
  size: number;
  /** The payload's name in the request folder for copy mode; `null` for link mode. */
  payload: string | null;
  provenance: ProvenanceValue | null;
}

/**
 * Assembles one inbox request (spec 5.10) and validates it against the
 * existing `InboxRequest` schema before it is ever written — this must
 * never produce a request `packages/format`'s own parser would reject.
 * Throws on failure: every field here is either generated by this
 * extension or already checked by its caller, so a schema mismatch is a
 * programmer error, not an expected outcome (AGENTS.md section 5).
 */
export function buildInboxRequest(input: BuildRequestInput): InboxRequestModel {
  const candidate = {
    format_version: 1,
    request_id: input.requestId,
    created: formatTimestamp(input.createdAt),
    created_by: `vscode-extension@${input.extensionVersion}`,
    experiment_id: input.experimentId,
    role: input.role,
    mode: input.mode,
    source: {
      root: "project" as const,
      path: toProjectRelativePath(input.projectRoot, input.filePath),
    },
    payload: input.payload,
    sha256: input.sha256,
    size: input.size,
    provenance: input.provenance,
  };
  const checked = InboxRequest.safeParse(candidate);
  if (!checked.success) {
    throw new Error(
      `built an invalid inbox request: ${checked.error.issues[0]?.message ?? "unknown error"}`,
    );
  }
  return checked.data;
}
