import { describe, expect, it } from "vitest";
import { readGolden } from "../../test/golden";
import { parseSectionMarkdown, serialiseSectionMarkdown } from "./markdown";
import { buildCitationNode, type CitationItem } from "./citation";

/**
 * Spec 5.7's own three examples plus its author-in-text example (S5-T03),
 * written by hand from docs/spec/specification.md, not generated by the
 * code under test — the same convention as
 * `packages/format/src/editor/references.golden.test.ts`.
 */

function docOf(...content: object[]) {
  return { type: "doc", content: [{ type: "paragraph", content }] };
}

const SINGLE_ITEMS: CitationItem[] = [
  {
    prefix: "",
    suppressAuthor: false,
    citekey: "z:u:7XK2PQ9M",
    suffix: "",
  },
];

const MULTI_ITEMS: CitationItem[] = [
  {
    prefix: "see ",
    suppressAuthor: false,
    citekey: "z:u:9HJ3LM2N",
    suffix: "fig. 2",
  },
  {
    prefix: "",
    suppressAuthor: false,
    citekey: "z:g4521:ABCD2345",
    suffix: "pp. 10-12",
  },
];

const SUPPRESS_AUTHOR_ITEMS: CitationItem[] = [
  {
    prefix: "",
    suppressAuthor: true,
    citekey: "z:u:7XK2PQ9M",
    suffix: "",
  },
];

describe("citation syntax matches spec 5.7 exactly", () => {
  it("single citekey", async () => {
    const text = serialiseSectionMarkdown(
      docOf(
        {
          type: "text",
          text: "PCA on variance-stabilised counts using DESeq2 ",
        },
        buildCitationNode(SINGLE_ITEMS),
        { type: "text", text: "." },
      ),
    );
    await expect(text).toMatchFileSnapshot("../__golden__/citation-single.md");
  });

  it("multiple citekeys with a prefix and locators", async () => {
    const text = serialiseSectionMarkdown(
      docOf(
        {
          type: "text",
          text: "The PC1 separation is consistent with the treatment response reported previously ",
        },
        buildCitationNode(MULTI_ITEMS),
        { type: "text", text: "." },
      ),
    );
    await expect(text).toMatchFileSnapshot("../__golden__/citation-multi.md");
  });

  it("suppress-author form", async () => {
    const text = serialiseSectionMarkdown(
      docOf(
        { type: "text", text: "This has been shown before " },
        buildCitationNode(SUPPRESS_AUTHOR_ITEMS),
        { type: "text", text: "." },
      ),
    );
    await expect(text).toMatchFileSnapshot(
      "../__golden__/citation-suppress-author.md",
    );
  });

  it("author-in-text form with a bracketed locator", async () => {
    const text = serialiseSectionMarkdown(
      docOf(
        {
          type: "citationInText",
          attrs: { citekey: "z:u:7XK2PQ9M", locator: "p. 4" },
        },
        { type: "text", text: " first described this effect." },
      ),
    );
    await expect(text).toMatchFileSnapshot("../__golden__/citation-in-text.md");
  });
});

describe("serialise(parse(file)) is byte-identical for the committed goldens", () => {
  it("single citekey", () => {
    const golden = readGolden("citation-single.md");
    expect(serialiseSectionMarkdown(parseSectionMarkdown(golden))).toBe(golden);
  });

  it("multiple citekeys with a prefix and locators", () => {
    const golden = readGolden("citation-multi.md");
    expect(serialiseSectionMarkdown(parseSectionMarkdown(golden))).toBe(golden);
  });

  it("suppress-author form", () => {
    const golden = readGolden("citation-suppress-author.md");
    expect(serialiseSectionMarkdown(parseSectionMarkdown(golden))).toBe(golden);
  });

  it("author-in-text form with a bracketed locator", () => {
    const golden = readGolden("citation-in-text.md");
    expect(serialiseSectionMarkdown(parseSectionMarkdown(golden))).toBe(golden);
  });
});
