import { describe, expect, it } from "vitest";
import { readGolden } from "../../test/golden";
import { parseSectionMarkdown, serialiseSectionMarkdown } from "./markdown";
import { buildArtefactRefNode } from "./artefactRef";

/**
 * Spec 5.6's own two examples (S4-G01), written by hand from
 * docs/spec/specification.md, not generated by the code under test — the
 * same convention as packages/format/src/files/formats.golden.test.ts.
 */

const COPY_MODE_ATTRS = {
  ulid: "01JAXR5D8K2M4N6P8Q0R2S4T6V",
  version: 2,
  label: "PCA by treatment",
  target: "evidence/pca_by_treatment.v2.pdf",
};

const LINK_MODE_ATTRS = {
  ulid: "01JAXR9Q1W3E5R7T9Y1V3J5N7P",
  version: null,
  label: "Raw counts",
  target: "../../../data/counts.h5",
};

function docOf(node: ReturnType<typeof buildArtefactRefNode>) {
  return {
    type: "doc",
    content: [{ type: "paragraph", content: [node] }],
  };
}

describe("reference syntax matches spec 5.6 exactly (S4-G01)", () => {
  it("copy mode", async () => {
    const text = serialiseSectionMarkdown(
      docOf(buildArtefactRefNode(COPY_MODE_ATTRS)),
    );
    await expect(text).toMatchFileSnapshot(
      "../__golden__/artefact-ref-copy.md",
    );
  });

  it("link mode", async () => {
    const text = serialiseSectionMarkdown(
      docOf(buildArtefactRefNode(LINK_MODE_ATTRS)),
    );
    await expect(text).toMatchFileSnapshot(
      "../__golden__/artefact-ref-link.md",
    );
  });
});

describe("serialise(parse(file)) is byte-identical for the committed goldens", () => {
  it("copy mode", () => {
    const golden = readGolden("artefact-ref-copy.md");
    expect(serialiseSectionMarkdown(parseSectionMarkdown(golden))).toBe(golden);
  });

  it("link mode", () => {
    const golden = readGolden("artefact-ref-link.md");
    expect(serialiseSectionMarkdown(parseSectionMarkdown(golden))).toBe(golden);
  });
});
