// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  The version of this build, recorded in `project.yaml` as
	 *  `last_written_by` (spec 5.3) so the frontend need not read it from
	 *  anywhere it could disagree with the Rust crate.
	 */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	/**
	 *  Generates a 256px-bounded PNG thumbnail for a PNG or JPEG image (spec
	 *  section 8). Spike for S1-T05: the first typed command in the app,
	 *  establishing the `apps/desktop/src/ipc/` generated-bindings boundary
	 *  that all future commands reuse (AGENTS.md section 4).
	 */
	previewThumbnailPng: (bytes: number[]) => typedError<number[], string>(__TAURI_INVOKE("preview_thumbnail_png", { bytes })),
	/**
	 *  Asks for a folder and creates a project in it (FR-PRJ-01). The texts are
	 *  built by `packages/format`. `None` when the person cancels.
	 */
	createProject: (projectYaml: string, bibliographyJson: string, evidenceInGit: boolean) => typedError<{
	folder: FolderHandle,
	/**  For display only. */
	path: string,
	hygiene: HygieneReport[],
} | null, ProjectError>(__TAURI_INVOKE("create_project", { projectYaml, bibliographyJson, evidenceInGit })),
	/**
	 *  Asks for a project folder and reads its `project.yaml` (FR-PRJ-02).
	 *  `None` when the person cancels.
	 */
	openProject: () => typedError<{
	folder: FolderHandle,
	/**  For display only. */
	path: string,
	projectYaml: string,
} | null, ProjectError>(__TAURI_INVOKE("open_project")),
	/**
	 *  Opens a project from the recent list without asking for its folder. A
	 *  folder that is gone, or no longer holds a project, is reported as
	 *  `folderUnavailable` or `notAProject`, and the person can then Locate it
	 *  (FR-PRJ-03).
	 */
	openRecentProject: (projectId: Ulid) => typedError<OpenedProject, ProjectError>(__TAURI_INVOKE("open_recent_project", { projectId })),
	/**
	 *  Asks for the folder a moved project is now in and reads its
	 *  `project.yaml`. The frontend checks the `id` matches the project being
	 *  located before it calls `remember_project`. `None` when cancelled.
	 */
	locateProject: () => typedError<{
	folder: FolderHandle,
	/**  For display only. */
	path: string,
	projectYaml: string,
} | null, ProjectError>(__TAURI_INVOKE("locate_project")),
	/**
	 *  Puts a project first in the recent list, or updates its path after it was
	 *  located. The identifier and name come from the parsed `project.yaml`.
	 */
	rememberProject: (folder: FolderHandle, projectId: Ulid, name: string) => typedError<null, ProjectError>(__TAURI_INVOKE("remember_project", { folder, projectId, name })),
	/**  The recent projects, most recent first, each marked available or not. */
	listRecentProjects: () => typedError<RecentEntry[], ProjectError>(__TAURI_INVOKE("list_recent_projects")),
	/**
	 *  Asks for the folder an external root of a project has on this machine and
	 *  remembers it (FR-PRJ-07). Returns the folder, or `None` when cancelled.
	 */
	setExternalRoot: (projectId: Ulid, rootId: Ulid) => typedError<string | null, ProjectError>(__TAURI_INVOKE("set_external_root", { projectId, rootId })),
	/**
	 *  Where each of a project's external roots is on this machine. The roots
	 *  come from the parsed `project.yaml`; an unresolved one marks the artefacts
	 *  linked through it unavailable.
	 */
	externalRootStatus: (projectId: Ulid, rootIds: Ulid[]) => typedError<ExternalRootStatus[], ProjectError>(__TAURI_INVOKE("external_root_status", { projectId, rootIds })),
	/**
	 *  Locks the project for writing and starts its heartbeat. Call it only for a
	 *  project that would otherwise be writable: a project that is read-only for
	 *  another reason gets no lock and no write of any kind. `confirm_takeover` is
	 *  true only after the person has agreed to take over a stale or unreadable lock.
	 */
	acquireProjectLock: (folder: FolderHandle, confirmTakeover: boolean) => typedError<LockOutcome, ProjectError>(__TAURI_INVOKE("acquire_project_lock", { folder, confirmTakeover })),
	/**
	 *  Whether the lock is still held. The webview asks now and then, so a lock
	 *  taken over while the project is open turns it read-only.
	 */
	projectLockState: (folder: FolderHandle) => typedError<LockState, ProjectError>(__TAURI_INVOKE("project_lock_state", { folder })),
	/**  Stops the heartbeat and removes the lock if it is still ours. */
	releaseProjectLock: (folder: FolderHandle) => typedError<null, ProjectError>(__TAURI_INVOKE("release_project_lock", { folder })),
	/**  Reads one notebook data file. Nothing is written. */
	readNotebookFile: (folder: FolderHandle, path: NotebookPath) => typedError<FileRead, ProjectError>(__TAURI_INVOKE("read_notebook_file", { folder, path })),
	/**
	 *  Overwrites a notebook data file with `text`, first keeping what it held in
	 *  `.history`. Refused, with nothing written, if this application does not
	 *  hold the project's lock, or if the file is no longer what `expected` says
	 *  (`changed`), which is how a save never overwrites an outside edit.
	 */
	writeNotebookFile: (folder: FolderHandle, path: NotebookPath, text: string, expected: ExpectedFile) => typedError<SaveResult, ProjectError>(__TAURI_INVOKE("write_notebook_file", { folder, path, text, expected })),
	/**
	 *  Moves a question file or an experiment folder to `.trash/`. Nothing is
	 *  deleted; the person can move it back.
	 */
	moveToTrash: (folder: FolderHandle, path: TrashTarget) => typedError<TrashedItem, ProjectError>(__TAURI_INVOKE("move_to_trash", { folder, path })),
	/**
	 *  Copies the notebook's text files to `backups/` before the first write by
	 *  this version of the application. The webview decides whether one is due by
	 *  comparing `last_written_by`, which it parsed, with this build's version;
	 *  the version named in the folder is this build's own, not one it supplies.
	 */
	backupForVersionChange: (folder: FolderHandle) => typedError<BackupMade, ProjectError>(__TAURI_INVOKE("backup_for_version_change", { folder })),
	/**
	 *  Starts watching the project's notebook files. Safe to call again for a
	 *  project already watched. Read-only projects are watched too: they still
	 *  show what changed on disk. Nothing is written.
	 */
	startProjectWatch: (folder: FolderHandle) => typedError<null, ProjectError>(__TAURI_INVOKE("start_project_watch", { folder })),
	/**  Takes the changes found since the last call. */
	pollProjectChanges: (folder: FolderHandle) => typedError<ChangeReport, ProjectError>(__TAURI_INVOKE("poll_project_changes", { folder })),
	/**  Stops watching the project. */
	stopProjectWatch: (folder: FolderHandle) => typedError<null, ProjectError>(__TAURI_INVOKE("stop_project_watch", { folder })),
};

/* Types */
/**  A backup that was made. */
export type BackupMade = {
	folder: string,
	copied: number,
	skipped: number,
};

/**  The changes found since the last poll. */
export type ChangeReport = {
	/**
	 *  False when the project is not being watched; there is then nothing to
	 *  report.
	 */
	watching: boolean,
	changes: ChangedFile[],
	/**
	 *  Events may have been lost, or a folder was moved, so every file the
	 *  webview holds should be checked again.
	 */
	needsRescan: boolean,
};

/**  One notebook data file that changed. The path is project-relative. */
export type ChangedFile = {
	path: string,
	state: ChangedState,
};

/**  What is on disk for a changed file. */
export type ChangedState = 
/**
 *  The file is there. `sha256` is of its content now, so the webview can
 *  tell its own save from someone else's edit.
 */
{ kind: "present"; sha256: string } | 
/**  The file is gone, or is a folder or link where a file should be. */
{ kind: "missing" } | 
/**  The file exists but could not be read for a while. */
{ kind: "unreadable" };

export type CreatedProject = {
	folder: FolderHandle,
	/**  For display only. */
	path: string,
	hygiene: HygieneReport[],
};

/**  What the caller believes is on disk. */
export type ExpectedFile = { kind: "absent" } | { kind: "sha256"; sha256: string };

/**  Where an external root of a project is on this machine (FR-PRJ-07). */
export type ExternalRootStatus = {
	rootId: string,
	/**  For display only; `None` when no folder has been chosen on this machine. */
	path: string | null,
	/**
	 *  False when there is no path or the folder is gone, which marks the
	 *  artefacts linked through it unavailable.
	 */
	available: boolean,
};

/**  What reading a notebook data file found. */
export type FileRead = 
/**  The file's text exactly as on disk, and the SHA-256 of those bytes. */
{ kind: "text"; text: string; sha256: string } | 
/**
 *  There is no such file now. Not an error: a file that was deleted
 *  after a change was reported is an ordinary outcome.
 */
{ kind: "missing" };

/**
 *  Stands for a folder the person chose in a native dialog. The webview holds
 *  this number, never the path, so it cannot name a folder it was not given
 *  (AGENTS.md rule 8).
 */
export type FolderHandle = number;

export type HygieneReport = {
	/**  `.gitignore` or `.gitattributes`. */
	file: string,
	status: HygieneStatus,
};

/**  What became of one repository hygiene file when a project was created. */
export type HygieneStatus = "added" | "unchanged" | 
/**  Not updated. The project exists; the entries can be added by hand. */
"failed";

/**  Who holds a lock and since when, for the banner. Times are RFC 3339 UTC. */
export type LockHolder = {
	host: string,
	pid: number,
	appVersion: string,
	opened: string,
	heartbeat: string,
};

/**
 *  The result of asking to lock a project. Only `acquired` allows writing;
 *  each other kind is a read-only reason with its own banner.
 */
export type LockOutcome = { kind: "acquired" } | 
/**  Held by another instance whose heartbeat is recent. */
{ kind: "live"; holder: LockHolder } | 
/**
 *  The heartbeat is five minutes old or more; taking over needs the
 *  person's confirmation.
 */
{ kind: "stale"; holder: LockHolder } | 
/**
 *  `.lock` is not a valid lock. When `replaceable`, taking over needs
 *  confirmation; otherwise it is a folder, link or read-only file.
 */
{ kind: "unreadable"; replaceable: boolean } | 
/**  The project's medium or folder does not allow writing. */
{ kind: "readOnlyMedia" };

/**  Whether this application still holds a project's lock. */
export type LockState = "held" | 
/**  Taken over by another instance, or the heartbeat failed. */
"lost" | "notHeld";

/**
 *  A project-relative path of a notebook data file, such as
 *  `_notebook/questions/Q-01.md`, checked so a command never receives free
 *  text where a path belongs. Backslashes are accepted and stored as `/`.
 */
export type NotebookPath = string;

/**
 *  A project folder that was opened. The text is `project.yaml` exactly as it
 *  is on disk; the frontend parses it with `packages/format`, the only parser.
 */
export type OpenedProject = {
	folder: FolderHandle,
	/**  For display only. */
	path: string,
	projectYaml: string,
};

/**
 *  Why a project command failed. The `kind` is the key of the user-facing
 *  message, which lives in the frontend's message files (spec 6.5); no path
 *  or system text is sent.
 */
export type ProjectError = 
/**  The folder cannot be used: it is missing or is not a folder. */
{ kind: "folderUnavailable" } | 
/**  The folder holds no `_notebook/project.yaml`. */
{ kind: "notAProject" } | 
/**  `_notebook` is a file or a link, or is spelt in another case. */
{ kind: "notebookInvalid" } | 
/**  Creating: `_notebook` already holds files, so nothing was written. */
{ kind: "alreadyInUse" } | 
/**  `project.yaml` exists but cannot be read as text. */
{ kind: "projectFileUnreadable" } | 
/**  Something was written and failed part way, or was refused. */
{ kind: "writeFailed" } | 
/**
 *  Nothing was written: this application does not hold the project's
 *  lock, so the project is read-only.
 */
{ kind: "notWritable" } | 
/**  The project lock could not be read, written or removed. */
{ kind: "lockFailed" } | 
/**
 *  A notebook data file could not be read: it is not one that may be read,
 *  is not a file, is not UTF-8 or could not be opened.
 */
{ kind: "fileUnavailable" } | 
/**  Watching the project for outside changes could not start. */
{ kind: "watchFailed" } | 
/**  No recent project has that identifier. */
{ kind: "notRemembered" } | 
/**  The settings file is damaged, and is left as it is. */
{ kind: "settingsDamaged" } | 
/**  The settings file was written by a newer version, and is left as it is. */
{ kind: "settingsNewer" } | 
/**  The settings file could not be read or written. */
{ kind: "settingsUnavailable" } | 
/**  A background task failed. Not caused by the person's input. */
{ kind: "internal" };

/**  A recent project as listed on the start screen. */
export type RecentEntry = {
	id: string,
	name: string,
	/**  For display only. */
	path: string,
	/**
	 *  False when the folder no longer holds a project, so the person can be
	 *  offered Locate project (FR-PRJ-03).
	 */
	available: boolean,
};

/**  What a save did. */
export type SaveResult = { kind: "saved"; snapshot: string | null } | { kind: "changed"; current: string | null };

/**
 *  A project-relative path the trash command accepts: a question file, or the
 *  folder of an experiment.
 */
export type TrashTarget = string;

/**  Where a trashed file or folder went. */
export type TrashedItem = {
	location: string,
};

/**
 *  A ULID that has been checked, so a command never receives free text where
 *  an identifier belongs. The value is only used as a key in the settings
 *  file, never as part of a path.
 */
export type Ulid = string;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

