// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Generates a 256px-bounded PNG thumbnail for a PNG or JPEG image (spec
	 *  section 8). Spike for S1-T05: the first typed command in the app,
	 *  establishing the `apps/desktop/src/ipc/` generated-bindings boundary
	 *  that all future commands reuse (AGENTS.md section 4).
	 */
	previewThumbnailPng: (bytes: number[]) => typedError<number[], string>(__TAURI_INVOKE("preview_thumbnail_png", { bytes })),
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

